### ISSUE TITLE
Latest SwiftLint Fails

### ISSUE THREAD

**Issue by ariveraati** [Adyen/AdyenCSE-iOS#11]
Looks like the podfile is not pinned to a specific SwiftLint version. The latest SwiftLint breaks the build of this framework.

**Comment by olutsenko** [comment]
Hello @ariveraati,

Not sure what do you mean. We don't include SwiftLint dependency in this project.

Regards,
Oleg

**Comment by ariveraati** [comment]
@olutsenko Apologies, we are actually seeing this error on this repository: https://github.com/Adyen/adyen-ios

I can close this one and file an issue there.
