### ISSUE TITLE
Sample code not provided under a permissive license

### ISSUE THREAD

**Issue by cysp** [Adyen/AdyenCSE-iOS#3]
Half of these files are marked `Copyright (c) … Adyen. All rights reserved.`, with the other half missing an explicit copyright assignment.
Is this sample code intended for customers to incorporate directly into their applications?
If so, could we get the files licensed under a suitable license?

**Comment by fpg1503** [comment]
The repo is now licensed as MIT but I'm not sure which information prevails.

**Comment by joostvandijk** [comment]
Hi @cysp,

Thanks for reporting this issue, and sorry for the late reply! We've updated the headers in all files to clarify the license.

Best,
Joost
