### ISSUE TITLE
NSDictionary category has a method without prefix

### ISSUE THREAD

**Issue by nikolaykasyanov** [Adyen/AdyenCSE-iOS#7]
Here it is: https://github.com/Adyen/adyen-cse-ios/blob/master/AdyenCSE/NSDictionary+AdyenUtil.h#L13

Apple [recommends](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/Conventions/Conventions.html) to prefix such methods.

**Comment by joostvandijk** [comment]
Hi @nikolaykasyanov,

Thanks for reporting this! I've fixed this in https://github.com/Adyen/adyen-cse-ios/commit/541fe8ea8734c5420462b2ea9cd7555641a9d700. A new release will be published next week.

Best,
Joost

**Comment by nikolaykasyanov** [comment]
@joostvandijk thank you!
