### ISSUE TITLE
Parse error: expected string after dependency type in line: github 'adyen/adyen-cse-ios'

### ISSUE THREAD

**Issue by ghost** [Adyen/AdyenCSE-iOS#8]
Issue:
Using github 'adyen/adyen-cse-ios' in Cartfile and trying carthage update throws following error:
Parse error: expected string after dependency type in line: github 'adyen/adyen-cse-ios'

Fix:
github "adyen/adyen-cse-ios" works fine :)

**Comment by joostvandijk** [comment]
Hi @PushpakN,

Thanks! Has been fixed. Sorry for the oversight.

Best,
Joost
